version: '3.1'

services:
  app:
    build: .
    container_name: todoList_app
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://admin:ox46o2vi9mG7XrX4RRD5OZlFmAR1qxuz@dpg-cr8tni56l47c73boltfg-a.ohio-postgres.render.com/stockcity_00bj
      - USE_REDIS=true
      - REDIS_URL=redis://redis-server:6379
    depends_on:
      - redis-server
  
  redis-server:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
