version: '3.1'

services:
  app:
    build: .
    container_name: todolist_app
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:ox46o2vi9mG7XrX4RRD5OZlFmAR1qxuz@database-1.cpa0oeeqeb6z.us-east-1.rds.amazonaws.com:5432/postgres
      - USE_REDIS=true
      - REDIS_URL=redis://redis-server:6379
    depends_on:
      - redis-server
  
  redis-server:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
