version: '3.1'

services:
  app:
    build: .
    container_name: todolist_app
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://admin:gdA9UopQABcBD3MdstAZLodXcWgTf2XI@dpg-cru0clhu0jms73c01860-a.ohio-postgres.render.com/stockcity_sedi
      - USE_REDIS=true
      - REDIS_URL=redis://redis-server:6379
    depends_on:
      - redis-server
  
  redis-server:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
